// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE_FAIEnglishTutor.Models;

public partial class Podcast
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? UserId { get; set; }

    public string Topic { get; set; }
}